version: '3.8'

services:
  database:
    build: ./database
    environment:
      POSTGRES_DB: citas_medicas
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
    volumes:
      - pgdata:/var/lib/postgresql/data

  proxy:
    build: ./proxi
    ports:
      - "80:80"  # Exponer el puerto 80 al host
    #depends_on:
    #  - backend
    #networks:
    #  - app-network

volumes:
  pgdata:
